
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myhfetljgzlyykvidnqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15aGZldGxqZ3pseXlrdmlkbnFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MTAzMzksImV4cCI6MjA2NjQ4NjMzOX0.5yacxS3fwxLgUbhOyOhsSfAN9SOgHCClrqmmZpJVlss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
