// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxyzuhhzwabkginrsyro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94eXp1aGh6d2Fia2dpbnJzeXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzM3ODEsImV4cCI6MjA2NzMwOTc4MX0.byojhZbjrhfMnC_nKOerbvlwna3IxD0c6J9oQ-BaxrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});